version: "3.1"

services:
  postgres:
    container_name: k8s-api-devs-db
    build:
      context: .
      dockerfile: dockerfileDB
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_conf:/etc/postgresql
      - pg_log:/var/log/postgresql

volumes:
  pg_data:
    driver: local
  pg_conf:
    driver: local
  pg_log:
    driver: local
